### ISSUE TITLE
Not Working on Unity 2022.3.49f1

### ISSUE THREAD

**Issue by Owen-Dechow** [walcht/com.walcht.ide.neovim#10]
On Linux Mint using Unity 2022.3.49f1 I get the following error: `Library/PackageCache/com.walcht.ide.neovim@a159538140/Editor/NeovimTerminalLaunchCmd.cs(57,20): error CS1061: 'TextField' does not contain a definition for 'verticalScrollerVisibility' and no accessible extension method 'verticalScrollerVisibility' accepting a first argument of type 'TextField' could be found (are you missing a using directive or an assembly reference?)`

**Comment by Owen-Dechow** [comment]
It does work if I comment out that line.
